### PR TITLE
add a flag for disable/enable multiple day events.

### PR DESCRIPTION
**Pull request by raftx24**
add a flag for disable/enable multiple day events.

### CODE REVIEW

**Comment by antoniandre** [comment]
Hi @raftx24,
Thanks for your contribution! 
But I don't think we need that, since the horizontal resizing is only enabled if the option `resize-x` is true [Line 532](https://github.com/antoniandre/vue-cal/pull/193/commits/bab91f746e8549c9116f204a09ff141b285f7647#diff-a647bec070b81754104655fa1601066cR532) (and `editable-events` needs to be true as well).

It means it is the option `resize-x` that dictates whether you can transform a single-day event in multiple-day event from resizing or not.

Besides, if the user puts a multiple-day event in the array of events the `multipleDayEvents` option won't prevent showing it as we would expect with this name.

Let me know if you had something else in mind that I did not get! :)

Cheers.

**Comment by raftx24** [comment]
Hi @antoniandre, imagine we want to have resize-x, but we don't want to have multiple day events.
In this scenario, we should be able to force the user to drag not more than one day.
We can check this flag for otherwhere too, but usually, we handle it from BE.

**Comment by antoniandre** [comment]
> imagine we want to have resize-x, but we don't want to have multiple day events

That's not possible.
The resize-x can't be used without multiple-day events, resize-x is not like resize on Y axis.
if you allow resize-x you obviously allow multiple-day.

If resize-x is allowed, mutliple-day is allowed, if resize-x is disabled you can't create multiple-day events but you if there was multiple-day events in the array of events they will display and you can resize them within the last day, but can't resize across different days.
I don't know if it's clearer now, please re-check this example where there are multiple-day events already: https://antoniandre.github.io/vue-cal/#ex--multiple-day-events.
If you disable resize-x you can still resize in y axis. And that's what we want.

**Comment by raftx24** [comment]
Oops!! you are entirely right! I made a mistake in reading docs.
Sorry.

**Comment by antoniandre** [comment]
That's alright no worries mate.

**Pull request closed without merging**
