### PR TITLE
Create Zh_cn.json

### PR DESCRIPTION
**Pull request by mano233**
Adding Simplified Chinese Support

### CODE REVIEW

**Comment by antoniandre** [comment]
Hi @mano233 ,
Thank you for your contribution, I have merged in but need to do a few corrections.

- I modified the date format to 'DDDD d mmmm yyyy' which is the format of what you can see in the full title of a single day view. Please tell me if it looks ok or tell me the full format of a correct full date in Chinese.
- please check the translation for 'years' and 'year' as it appears to be the same. The 'years' view contains multiple years, maybe if there is no plural of 'year' is there something like 'all years'?
- for consistency and simplicity I have renamed the file into 'zh-cn.json', to use it the locale will be 'zh-cn'.

I will release it as is for now and will add your modifications later on.

Thank you for your input again!

**Comment by mano233** [comment]
- sorry,  "years" mybe translated "全年" .I don't know where this "years" is used.
- For "full format",for example "2018年 12月16日 周三"

- I just did a translation and I haven't tested it yet.

**Comment by mano233** [comment]
> Hi @mano233 ,
> Thank you for your contribution, I have merged in but need to do a few corrections.
> 
> * I modified the date format to 'DDDD d mmmm yyyy' which is the format of what you can see in the full title of a single day view. Please tell me if it looks ok or tell me the full format of a correct full date in Chinese.
> * please check the translation for 'years' and 'year' as it appears to be the same. The 'years' view contains multiple years, maybe if there is no plural of 'year' is there something like 'all years'?
> * for consistency and simplicity I have renamed the file into 'zh-cn.json', to use it the locale will be 'zh-cn'.
> 
> I will release it as is for now and will add your modifications later on.
> 
> Thank you for your input again!

- sorry, "years" mybe translated "全年" .I don't know where this "years" is used.
- 
- For "full format",for example "2018年 12月16日 周三"
- 
- I just did a translation and I haven't tested it yet.

**Comment by mano233** [comment]
- For "full format",for example "2018年 12月16日 周三"
-  "年" not  have multiple.I don't know where "years" is used.
- I just did a translation and I haven't tested it yet.image

**Comment by mano233** [comment]
> Hi @mano233 ,
> Thank you for your contribution, I have merged in but need to do a few corrections.
> 
> * I modified the date format to 'DDDD d mmmm yyyy' which is the format of what you can see in the full title of a single day view. Please tell me if it looks ok or tell me the full format of a correct full date in Chinese.
> * please check the translation for 'years' and 'year' as it appears to be the same. The 'years' view contains multiple years, maybe if there is no plural of 'year' is there something like 'all years'?
> * for consistency and simplicity I have renamed the file into 'zh-cn.json', to use it the locale will be 'zh-cn'.
> 
> I will release it as is for now and will add your modifications later on.
> 
> Thank you for your input again!

- For "full format",for example "2018年 12月16日 周三"
- "年" not have multiple.I don't know where "years" is used.
- I just did a translation and I haven't tested it yet.
image

**Comment by mano233** [comment]
> Hi @mano233 ,
> Thank you for your contribution, I have merged in but need to do a few corrections.
> 
> * I modified the date format to 'DDDD d mmmm yyyy' which is the format of what you can see in the full title of a single day view. Please tell me if it looks ok or tell me the full format of a correct full date in Chinese.
> * please check the translation for 'years' and 'year' as it appears to be the same. The 'years' view contains multiple years, maybe if there is no plural of 'year' is there something like 'all years'?
> * for consistency and simplicity I have renamed the file into 'zh-cn.json', to use it the locale will be 'zh-cn'.
> 
> I will release it as is for now and will add your modifications later on.
> 
> Thank you for your input again!

I will test

**Comment by mano233** [comment]
image
it work,but there are still some things that do not conform to Chinese customs. I will continue to pay attention to them.


{
  "weekDays": ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日"],
  "months": ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
  "years": "年",
  "year": "本年",
  "month": "月",
  "week": "周",
  "day": "日",
  "today": "今日",
  "noEvent": "暂无活动",
  "deleteEvent": "删除",
  "createEvent": "新建活动",
  "dateFormat": "yyyy mmmm d DDDD"
}
@antoniandre

**Comment by antoniandre** [comment]
Thank you @mano233 , version 1.3.1 includes these changes.

**Pull request merged**
