### PR TITLE
chore(i18n): add pt-pt locale

### PR DESCRIPTION
**Pull request by mcasx**
Adds pt-pt locale

### CODE REVIEW

**Comment by mcasx** [comment]
@antoniandre Is it possible to have this merged? 😄

**Comment by antoniandre** [comment]
@mcasx, yes. But as I'm merging in, I'm seeing that it's exactly the same file as pt-br. If that's the case maybe we don't need different files and can call it `pt` only?
Before I publish, please review that and let me know. Either we update one of the files, or we merge them.

**Comment by mcasx** [comment]
> @mcasx, yes. But as I'm merging in, I'm seeing that it's exactly the same file as pt-br. If that's the case maybe we don't need different files and can call it `pt` only? Before I publish, please review that and let me know. Either we update one of the files, or we merge them.

@antoniandre First of all thank you for your work on this repo, me and many others value it a lot!
It's true, the translations for those two are exactly the same in these cases, they may diverge if we add some more locale. I would keep them separate but up to you, happy to merge them.

**Comment by antoniandre** [comment]
Makes sense. Merged in version 4.9.0

**Pull request merged**
