### PR TITLE
DragEventCreation

### PR DESCRIPTION
**Pull request by Csandori**
New method for event creation. Press and pull for event creation like in google calendar.

### CODE REVIEW

**Comment by r32rf** [comment]
~~Hi, I have been testing this.  The calendar rapidly emits `cell-click` when dragging a new event.  Is that intended?~~  
Resolved :-) Thanks @Csandori

**Comment by antoniandre** [comment]
Hi @Csandori,
Thanks for your good work, that's great!
I was considering to add this feature and never had time.

I have a few concerns that will need some tedious modification from you though, sorry about that part:
- Please pull master into your code
- **Please respect the linting styles in place in the codebase**: for instance no semi-column, simple quotes in Javascript, space before parenthesis on method definition, etc. Unfortunately It looks like you have reformatted the whole files you worked in. So it's really hard for me to go through the changes before accepting, there must be a thousand lines changed due to the formatting. :/
   the linter is all setup in vue-cal codebase but there is currently an issue https://github.com/babel/babel-eslint/issues/681#issuecomment-595591823 that prevents running in the background.
   You always run `npm run lint` and `npm run lint --fix` it will correct a fair amount of issues for you 👍 

- Please put back the CSS you did not change as it was.
- Please respect the naming convention in place in the codebase: all the emitted events are `kebab-case`.
- If an instruction is on a single line, leave it on a single line.

Last but not least, please don't do a pull request before you are done or before you are done testing.

You can also create an issue where we can discuss a new feature  before you start it if it's not small changes, might end up useful :)

Sorry to make you change your formatting now, but it should be straightforward with the help of `npm run lint`.

Thanks for your contribution again it looks quite promising, I will test it and review it when you are done. 😉 

Cheers!

**Comment by Csandori** [comment]
It's totally fine, thanks for reviewing. This is my first attempt to contribute, so every help appreciated. I'm on it :)

**Comment by antoniandre** [comment]
Awesome, I haven't tested but I'm sure you're doing a great feature. 
Thanks @r32rf for your help testing as well.

**Comment by Csandori** [comment]
Ok, I think I've done everything you asked. If not let me know :)

**Comment by antoniandre** [comment]
This looks great @Csandori!
Thanks for this great feature and reformatting, I will merge it soon and review it. 
Sorry it's been dragging for some time, I am very busy atm.

**Comment by antoniandre** [comment]
This is really some good work @Csandori, love it. 👏👏
I will integrate it with more constraints and options and document it. 
Will let you know when ready

**Comment by antoniandre** [comment]
We also need to check mousemove mouseup on the whole document so there is no problem when dragging and releasing outside of the cell or split. I'll add that

**Comment by antoniandre** [comment]
For information I moved this whole feature in the `drag-event-creation` branch as it still needs some dev.
I will work in it until I merge back to master.

if ever you you do some change please do it there and pull regularly.
The master is currently reverted so I can do urgent patches.
You should pull that one too if you plan to do other PRs.

**Comment by antoniandre** [comment]
Hi @Csandori, 
Quick heads-up regarding this PR: I have finished refactoring and adding new features on top of this. It looks great.
I now need to write the documentation and update all the example about event creation.

Thanks for your work again! 
Now that you know the codebase, you would be nailing new features!
If ever you want to get onboard on Vue Cal dev, let's get in touch via email.
My email is in the package.json.

Cheers!

**Comment by Csandori** [comment]
Great!

Looking forward for the release!

I've already sent the email.

**Comment by antoniandre** [comment]
Hi @Csandori, it is now live: https://antoniandre.github.io/vue-cal/#release-notes 3.5.0!
PS. Will reply to your email soon.

**Pull request merged**
