### PR TITLE
✏️ Typo in i18n: Norwegian

### PR DESCRIPTION
**Pull request by rubjo**

### CODE REVIEW

**Comment by antoniandre** [comment]
Thank you for the PR, merged and release in version 3.10.2.
Sorry for the biiig delay.

**Comment by Guenther93** [comment]
Is it possible whatever you just merged broke all the labels - my entire calendar is showing "undefined" now pointing at...https://unpkg.com/vue-cal

**Comment by antoniandre** [comment]
Could you share a repro?
It seem to work fine on all the examples of the documentation. Also in Norwegian

**Comment by Guenther93** [comment]
While working on trying get you a sample that works I figured out the problem somewhat...

I was pinned at vue 2.6.12 - which when combined with vue-cal 3.10.1 works but 3.10.2 the labels disappear and 3.10.3 the labels show "undefined".

Not sure what a 3rd level sub release would cause this - but I am at least able to temporarily work around it while I look to determine why we were pinned at the 2.6.12 version. 

https://jsfiddle.net/Guenther93/jp3cekL0/3/ <- vue 2.6.12 with vue-cal 3.10.1 - "working"
https://jsfiddle.net/Guenther93/3t4ozwf2/2/ <- vue 2.6.12 with vue-cal 3.10.3 - "undefined labels"
https://jsfiddle.net/Guenther93/dy5x2ko1/2/ <- vue 2.6.13 with vue-cal 3.10.3 - "empty labels"
https://jsfiddle.net/Guenther93/avk2tre9/1/ <- vue 2.6.14 with vue-cal 3.10.3 - "working"

**Comment by antoniandre** [comment]
Thanks for all the repro. It can be because of some slot syntax, but as long as the last version of Vue 2 works for vue-cal vue 2 that's what matters. :)
Let me know if you can unpin the Vue version. You should use the latest Vue 2.

**Pull request merged**
