### PR TITLE
Greek translation

### PR DESCRIPTION
**Pull request by BobSynfig**
Hi,
here is the Greek translation for vue-cal.
As it uses Genitive form for the full date format, I also added in date-utils.
It could be used by some other languages too.
Feel free to change the format template "mmmmG" if you prefer another one. :)

### CODE REVIEW

**Comment by antoniandre** [comment]
Thanks for your contribution @BobSynfig!
Mmm, I understand this genitive form, that's annoying Greek language has this! 
Well we want to make it work for this language too, so not much choice and you found a way around it. 👌 

Before I release it, do you think I should add the translations for `am`/`pm`? 
I've seen `μ.μ.`/`π.μ.`, Is this also a valid format in Greek? 

Thanks!

**Comment by BobSynfig** [comment]
Yes, you could add it too :)
We use both notations (12 & 24) but the official one is π.μ./μ.μ.

But be careful :
('am', 'pm') -> ('π.μ.', 'μ.μ.')

https://el.wikipedia.org/wiki/Ώρα

Thanks to you :)

**Comment by antoniandre** [comment]
All good, it's now published in version 2.11.1!

**Comment by BobSynfig** [comment]
Thanks a lot!

**Pull request merged**
